### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nestorcolt** [FX31337/ex4_to_mq4_cli#2]
Any usage docs for this project?

**Comment by kenorb** [comment]
1. The requirement is to have the original decompiler `ex4_to_mq4.exe`, or `ex4_to_mq4_demo.exe` for testing purposes. The execution file is defined as `EXE_NAME` in `ex4_to_mq4_auto.c`.
2. You compile the project as `ex4_to_mq4_auto.exe` which acts as a wrapper.
3. You run `ex4_to_mq4_auto.exe` with files as arguments to decompile.

You need to install [DosBox Injector](https://sourceforge.net/projects/dbi/). It was tested with a CodeLite from 12/21/10 (check: [DosBox Injector's `dosbox_injector.mk` file](https://sourceforge.net/p/dbi/code/HEAD/tree/trunk/dosbox_injector.mk#l17) as for the example), other than that you don't need any special libraries to compile it.

Please note this is not the decompiler it self, it's a wrapper. See also: GH-1
Let me know if that helps.

**Comment by Sloter2019** [comment]
Hi, good kenorb, I got in touch with you to ask how I can compile this file or what program I need to compile to get the .exe I do not know how to do it. I would really appreciate it if you could help me

**Comment by kenorb** [comment]
> How I can compile this file or what program I need to compile to get the .exe I do not know how to do it.

See: <https://github.com/FX31337/ex4_to_mq4_cli/issues/4>
