### ISSUE TITLE
ex4_to_mq4 Can it really be done?

### ISSUE THREAD

**Issue by sujinda123** [FX31337/ex4_to_mq4_cli#3]
Please tell me how to change ex4 to mq4 for me
I am experiencing this problem alone.
If there are examples too, it will be very good.

[BinaryProfit.zip](https://github.com/FX31337/ex4_to_mq4_cli/files/2713981/BinaryProfit.zip)

**Comment by ahangarha** [comment]
This looks like to be fake

**Comment by kenorb** [comment]
This project is the wrapper for the existing EX4-TO-MQ4 Decompiler to support command-line conversion. If you don't have EX4-TO-MQ4 Decompiler, then this project won't be useful for you.

Dup of GH-1
