### ISSUE TITLE
Cannot build exe

### ISSUE THREAD

**Issue by joe76smith** [FX31337/ex4_to_mq4_cli#4]
I've tried building in CodeLite and VS. What are you using to compile the project? I get various errors depending on what I'm using. Any advice would be helpful. I spent 5 days trying to compile the project before writing this.

**Comment by kenorb** [comment]
Have you tried to compile using _CodeLite IDE_, and opening the project (`.project`) or makefile (`.mk`) file?

**Comment by antdlt** [comment]
Same for me, impossible to build with CodeLite :

`C:\WINDOWS\system32\cmd.exe /C C:/MinGW/mingw32/bin/mingw32-make.exe -j8 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ ex4_to_mq4_cli - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/XXXXXXXXXX/ex4_to_mq4_cli'
C:/MinGW/mingw32/bin/g++.exe -o ./Debug/ex4_to_mq4_cli @"ex4_to_mq4_cli.txt" -L. -L. -LDebug   -O0
./Debug/ex4_to_mq4_auto.cpp.o: In function 'main':
C:/XXXXXXXXXX/ex4_to_mq4_cli/ex4_to_mq4_auto.cpp:72: multiple definition of 'main'`

`./Debug/ex4_to_mq4_auto.c.o:ex4_to_mq4_auto.c:(.text+0xcb): first defined here
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0x802): undefined reference to 'MODE_CHECK_ADDR'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xc82): undefined reference to 'FETCH8'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xcc4): undefined reference to 'FETCH16'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xce8): undefined reference to 'FETCH32'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xde1): undefined reference to 'MODE_CHECK_OPERAND'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xe0d): undefined reference to 'FETCH8'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xe8d): undefined reference to 'FETCH32'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xe9f): undefined reference to 'FETCH16'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xed3): undefined reference to 'FETCH16'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xf23): undefined reference to 'MODE_CHECK_OPERAND'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xf4f): undefined reference to 'FETCH32'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xf5c): undefined reference to 'FETCH16'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xf7b): undefined reference to 'FETCH16'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0xfdf): undefined reference to 'FETCH8'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0x1022): undefined reference to 'FETCH32'
./Debug/scit_libdasm_libdasm.c.o:libdasm.c:(.text+0x102f): undefined reference to 'FETCH16'
./Debug/scit_scit.c.o:scit.c:(.text+0x10f0): undefined reference to 'EnumProcesses@12'
./Debug/scit_scit.c.o:scit.c:(.text+0x11c2): undefined reference to 'GetModuleBaseNameA@16'
./Debug/scit_scit.c.o:scit.c:(.text+0x139d): undefined reference to '_imp___scitRemoteUnhookExports_EAT@4'
./Debug/scit_scit.c.o:scit.c:(.text+0x148b): undefined reference to '_imp___scitRemoteHookAPI@4'
./Debug/scit_scit.c.o:scit.c:(.text+0x373b): undefined reference to '_imp___scitRemoteBackupAPICode@4'`

`collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[1]: *** [ex4_to_mq4_cli.mk:81: Debug/ex4_to_mq4_cli] Error 1
mingw32-make.exe: *** [Makefile:5: All] Error 2
mingw32-make.exe[1]: Leaving directory 'C:/XXXXXXXXXX/ex4_to_mq4_cli'`

`====22 errors, 0 warnings====`

Have you an idea ?

**Comment by kenorb** [comment]
> undefined reference to 'FETCH8'

> undefined reference to 'FETCH16'

As per definition, make sure you've defined `__X86__`?

```
__inline__ DWORD FETCH32(BYTE *addr) {
#if defined __X86__
	return *(DWORD *)addr;
#else
```

**Comment by antdlt** [comment]
What do you means about defined `__X86__` ? It is 32bit version of decompiler on a 64bit machine, that is the problem ?

I tried on another PC (W7) but I got the same error..

Thank for your help !

**Comment by kenorb** [comment]
I've a friend who was writing this code for me. He told me that you need a CodeLite from 12/21/10 (check: [DosBox Injector's `dosbox_injector.mk` file](https://sourceforge.net/p/dbi/code/HEAD/tree/trunk/dosbox_injector.mk#l17) as for the example), other than that you don't need any special libraries to compile it.

**Comment by h0ttz** [comment]
Did you make that code works ?
