### ISSUE TITLE
The decompiler?

### ISSUE THREAD

**Issue by pedrosimao** [FX31337/ex4_to_mq4_cli#5]
Where can I find the decompiler (and not the wrapper)?

**Comment by antdlt** [comment]
> Where can I find the decompiler (and not the wrapper)?

http://forexstay.com/download/ea/Ex4%20Decomplier%20(ex4%20to%20mq4)/

**Comment by pedrosimao** [comment]
Thanks a lot.
So, it only works with very old build (2013) I suppose, right?

**Comment by antdlt** [comment]
Yep, uploaded in 2009 if you see ;)

**Comment by rajeshvlr83** [comment]
there is no decompiler  for present version...

**Comment by rajeshvlr83** [comment]
dont waste time and money if somebody say he can decompile ex4 to mq4

**Comment by kenorb** [comment]
> dont waste time and money if somebody say he can decompile ex4 to mq4

This is the wrapper, not decompiler. You need to have decompiler present. There is one, but it works only for older versions of EX4.

**Comment by Roc123456789** [comment]
> > dont waste time and money if somebody say he can decompile ex4 to mq4
> 
> This is the wrapper, not decompiler. You need to have decompiler present. There is one, but it works only for older versions of EX4.

> how can i remove Demo limitation on .EX4 file ?

**Comment by Roc123456789** [comment]
> > dont waste time and money if somebody say he can decompile ex4 to mq4
> 
> This is the wrapper, not decompiler. You need to have decompiler present. There is one, but it works only for older versions of EX4.

> one person remove EX4 file limitation in only 1 minutes new file also ..how can he do that any idea ?

**Comment by Roc123456789** [comment]
> dont waste time and money if somebody say he can decompile ex4 to mq4

you are wrong ......Available for New Built also but that person doesnot sell decompiler ..only decompil EX4 file .....with 600$

**Comment by Roc123456789** [comment]
[ex4_to_mq4 2019.zip](https://github.com/FX31337/ex4_to_mq4_cli/files/3511670/ex4_to_mq4.2019.zip)
this person do this work ...

**Comment by kenorb** [comment]
> [ex4_to_mq4 2019.zip](https://github.com/FX31337/ex4_to_mq4_cli/files/3511670/ex4_to_mq4.2019.zip)
> this person do this work ...

600USD in advance for a single EX4 decompilation? Looks like scam for me. If won't work, they won't give you money back. This app is not a decompiler, it's just tell you to pay and send the EX4 via e-mail. Waste of money.

**Comment by Roc123456789** [comment]
> > [ex4_to_mq4 2019.zip](https://github.com/FX31337/ex4_to_mq4_cli/files/3511670/ex4_to_mq4.2019.zip)
> > this person do this work ...
> 
> 600USD in advance for a single EX4 decompilation? Looks like scam for me. If won't work, they won't give you money back. This app is not a decompiler, it's just tell you to pay and send the EX4 via e-mail. Waste of money.

do you know how to remove demo from ex4 ?

**Comment by kenorb** [comment]
Try: <http://www.pewasoft.com/.mt4/decompiler/>.

**Comment by kenorb** [comment]
For some other help with EAs/MQL, you may ask at: https://t.me/EA31337
