### ISSUE TITLE
There are issues in  building the project.

### ISSUE THREAD

**Issue by JafferWilson** [FX31337/ex4_to_mq4_cli#6]
Can you please give a released version of the exe file and the usage with the decompiler? I have the decompiler and I was tying to create this wrapper for it but could not as I am facing errors.
I have used the codelite for the compilation.
```
C:\WINDOWS\system32\cmd.exe /C ""C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/mingw32-make.exe" -j4 SHELL=cmd.exe -e -f  Makefile"
"----------Building project:[ ex4_to_mq4_cli_master - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Users/NEW_AIMS/Desktop/ex4_to_mq4_cli-master'
"C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++.exe" -o Debug/ex4_to_mq4_cli_master @"ex4_to_mq4_cli_master.txt" -L. -L. -LDebug   -O0 -lpsapi
Debug/scit_scit.c.o:scit.c:(.text+0x139d): undefined reference to `_imp___scitRemoteUnhookExports_EAT@4'
Debug/scit_scit.c.o:scit.c:(.text+0x148b): undefined reference to `_imp___scitRemoteHookAPI@4'
Debug/scit_scit.c.o:scit.c:(.text+0x373b): undefined reference to `_imp___scitRemoteBackupAPICode@4'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[1]: *** [ex4_to_mq4_cli_master.mk:81: Debug/ex4_to_mq4_cli_master] Error 1
mingw32-make.exe: *** [Makefile:5: All] Error 2
mingw32-make.exe[1]: Leaving directory 'C:/Users/NEW_AIMS/Desktop/ex4_to_mq4_cli-master'
====3 errors, 0 warnings====

```

**Comment by kenorb** [comment]
You need a [CodeLite](https://sourceforge.net/projects/codelite/files/Releases/) (check: [DosBox Injector's `dosbox_injector.mk` file](https://sourceforge.net/p/dbi/code/HEAD/tree/trunk/dosbox_injector.mk#l17) as for the example), other than that you don't need any special libraries to compile it as far as I know. If won't work, try older version of CodeLite (e.g. v2.9 or above).

**Comment by JafferWilson** [comment]
Is it possible for you to release an executable version of it? Also, if not then can you share a video that show how to run the repository? Is it working at all. Otherwise I am just trying and everything is in vain.

**Comment by JafferWilson** [comment]
Can you tell me what it exactly do, using the decompiler?

**Comment by kenorb** [comment]
> Is it possible for you to release an executable version of it?

I'm not dealing with it anymore, I won't have time unfortunately. Also I wasn't the one programming it.

**Comment by kenorb** [comment]
> Can you tell me what it exactly do, using the decompiler?

It implements CLI extension for existing decompiler to decompile files in batch, instead of drag&drop. So it's not a decompiler it-self.

**Comment by JafferWilson** [comment]
Thank you very much for your insights.

**Comment by JafferWilson** [comment]
Can I ask you, whether you know how to decompile using anything else?

**Comment by JafferWilson** [comment]
I mean you know anything else like tool or method that would help me. I guess the file that I am using in the MT4 is abusive and malicious. Hence, I am trying to know what is inside. I try to report the mql5 community but there was  no heed.

**Comment by kenorb** [comment]
> Can I ask you, whether you know how to decompile using anything else?

The existing decompiler only was able to handle files for very old builds. Nowadays I don't know any working decompiler. The author doesn't sell it anymore, and everything else is likely to be a scam.

**Comment by JafferWilson** [comment]
Yes you are absolutely correct. Anyways thank you for help.
