### ISSUE TITLE
Where is decompiler to use this wrapper?

### ISSUE THREAD

**Issue by eliteguru1226** [FX31337/ex4_to_mq4_cli#8]
These codes are for wrapper, not for decompiler.
So it needs "ex4_to_mq4_demo.exe" or something.
Where is it?
@antdlt said "http://forexstay.com/download/ea/Ex4%20Decomplier%20(ex4%20to%20mq4)/", but nothing is in there.

**Comment by kenorb** [comment]
I don't know where you can find it.
It was available at https://purebeam.biz/files/ex4_to_mq4_demo.exe, but it has been removed.

**Comment by kenorb** [comment]
Try: <http://www.pewasoft.com/.mt4/decompiler/>.

Dup of: #5.
